name: landsat-product-cookbook-dev
channels:
  - conda-forge
dependencies:
  - python>=3.12
  - jupyterlab=4.0.13
  - mystmd
  - jupyterlab-myst
  - xarray=2024.05.0
  - pygmt
  - scikit-image
  - gdal
  - pystac-client
  - pyproj
  - pandas
  - geopandas
  - intake=0.7.0
  - intake-esm=2024.2.6
  - earthaccess
  - scikit-learn
  - ipywidgets
  - tqdm
  - boto3
  - rasterio
  - dask
  - rioxarray
  - cartopy
  - scipy
  - shapely
  - statsmodels
  - cycler
  - pytest
  - nbmake
  - matplotlib
  - ipympl
  - geoviews
  - hvplot
  - seaborn
  - prettytable
  - metpy
  - pykrige
  - pip
  - pip:
    - pytensor
    - pymc
