name: landsat-product-cookbook-dev
channels:
  - conda-forge
dependencies:
  - jupyterlab=4.0.13
  - intake=0.7.0
  - intake-esm=2024.2.6
  - mystmd
  - jupyterlab-myst
  - pygmt
  - scikit-image
  - gdal
  - pystac-client
  - pyproj
  - geopandas
  - earthaccess
  - scikit-learn
  - ipywidgets
  - tqdm
  - dask
  - metpy
  - statsmodels
  - seaborn
  - pytest
  - ipympl
  - hvplot
  - geoviews
  - prettytable
  - pytensor
  - pymc
