name: landsat-product-cookbook
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - adwaita-icon-theme=48.1
  - affine=2.4.0
  - aiobotocore=2.23.2
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aioitertools=0.12.0
  - aiosignal=1.4.0
  - annotated-types=0.7.0
  - anyio=4.10.0
  - aom=3.9.1
  - appdirs=1.4.4
  - argon2-cffi=25.1.0
  - argon2-cffi-bindings=25.1.0
  - arrow=1.3.0
  - arviz=0.22.0
  - asciitree=0.3.3
  - asttokens=3.0.0
  - async-lru=2.0.5
  - at-spi2-atk=2.38.0
  - at-spi2-core=2.40.3
  - atk-1.0=2.38.0
  - attrs=25.3.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.5
  - aws-c-http=0.10.4
  - aws-c-io=0.21.2
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.6
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.33.1
  - aws-sdk-cpp=1.11.606
  - azure-core-cpp=1.16.0
  - azure-identity-cpp=1.12.0
  - azure-storage-blobs-cpp=12.14.0
  - azure-storage-common-cpp=12.10.0
  - azure-storage-files-datalake-cpp=12.12.0
  - babel=2.17.0
  - beautifulsoup4=4.13.4
  - binutils_impl_linux-64=2.44
  - binutils_linux-64=2.44
  - blas=2.133
  - blas-devel=3.9.0
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - blosc=1.21.6
  - bokeh=3.7.3
  - boto3=1.39.8
  - botocore=1.39.8
  - bounded-pool-executor=0.0.3
  - branca=0.8.1
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-blosc2=2.19.1
  - ca-certificates=2025.8.3
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cachetools=6.1.0
  - cairo=1.18.4
  - cartopy=0.25.0
  - certifi=2025.8.3
  - cffi=1.17.1
  - cftime=1.6.4
  - charls=2.4.2
  - charset-normalizer=3.4.2
  - click=8.2.1
  - click-plugins=1.1.1.2
  - cligj=0.7.2
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - colorcet=3.1.0
  - comm=0.2.3
  - conda-gcc-specs=14.3.0
  - cons=0.4.7
  - contourpy=1.3.3
  - curl=8.14.1
  - cycler=0.12.1
  - cytoolz=1.0.1
  - dask=2025.7.0
  - dask-core=2025.7.0
  - datashader=0.18.2
  - dav1d=1.2.1
  - dbus=1.16.2
  - dcw-gmt=2.2.0
  - debugpy=1.8.16
  - decorator=5.2.1
  - defusedxml=0.7.1
  - deprecated=1.2.18
  - distributed=2025.7.0
  - earthaccess=0.14.0
  - entrypoints=0.4
  - epoxy=1.5.10
  - etuples=0.3.10
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - fasteners=0.19
  - fastprogress=1.0.3
  - fftw=3.3.10
  - filelock=3.18.0
  - flexcache=0.3
  - flexparser=0.4
  - folium=0.20.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.0
  - fqdn=1.5.1
  - freetype=2.13.3
  - freexl=2.0.0
  - fribidi=1.0.10
  - frozenlist=1.7.0
  - fsspec=2025.7.0
  - gcc=14.3.0
  - gcc_impl_linux-64=14.3.0
  - gcc_linux-64=14.3.0
  - gdal=3.10.3
  - gdk-pixbuf=2.42.12
  - geopandas=1.1.1
  - geopandas-base=1.1.1
  - geos=3.13.1
  - geotiff=1.7.4
  - geoviews=1.14.0
  - geoviews-core=1.14.0
  - gflags=2.2.2
  - ghostscript=10.04.0
  - giflib=5.2.2
  - glib-tools=2.84.3
  - glog=0.7.1
  - gmt=6.5.0
  - graphite2=1.3.14
  - graphviz=13.1.1
  - gshhg-gmt=2.3.7
  - gtk3=3.24.43
  - gts=0.7.6
  - gxx=14.3.0
  - gxx_impl_linux-64=14.3.0
  - gxx_linux-64=14.3.0
  - h2=4.2.0
  - h5netcdf=1.6.4
  - h5py=3.13.0
  - harfbuzz=11.3.3
  - hdf4=4.2.15
  - hdf5=1.14.3
  - hicolor-icon-theme=0.17
  - holoviews=1.21.0
  - hpack=4.1.0
  - hvplot=0.12.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - imagecodecs=2025.8.2
  - imageio=2.37.0
  - importlib-metadata=8.7.0
  - importlib-resources=6.5.2
  - importlib_metadata=8.7.0
  - importlib_resources=6.5.2
  - iniconfig=2.0.0
  - intake=0.7.0
  - intake-esm=2024.2.6
  - ipykernel=6.30.1
  - ipympl=0.9.7
  - ipython=9.4.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - isoduration=20.11.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jmespath=1.0.1
  - joblib=1.5.1
  - json-c=0.18
  - json5=0.12.0
  - jsonpointer=3.0.0
  - jsonschema=4.25.0
  - jsonschema-specifications=2025.4.1
  - jsonschema-with-format-nongpl=4.25.0
  - jupyter-lsp=2.2.6
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.0.13
  - jupyterlab-myst=2.4.2
  - jupyterlab_pygments=0.3.0
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.15
  - jxrlib=1.1
  - kerchunk=0.2.7
  - kernel-headers_linux-64=3.10.0
  - keyutils=1.6.1
  - kiwisolver=1.4.8
  - krb5=1.21.3
  - lark=1.2.2
  - lazy-loader=0.4
  - lcms2=2.17
  - ld_impl_linux-64=2.44
  - lerc=4.0.0
  - libabseil=20250512.1
  - libaec=1.1.4
  - libarchive=3.8.1
  - libarrow=21.0.0
  - libarrow-acero=21.0.0
  - libarrow-compute=21.0.0
  - libarrow-dataset=21.0.0
  - libarrow-substrait=21.0.0
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.14.1
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgcc=15.1.0
  - libgcc-devel_linux-64=14.3.0
  - libgcc-ng=15.1.0
  - libgd=2.3.3
  - libgdal-core=3.10.3
  - libgdal-jp2openjpeg=3.10.3
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libglib=2.84.3
  - libgomp=15.1.0
  - libgoogle-cloud=2.39.0
  - libgoogle-cloud-storage=2.39.0
  - libgrpc=1.73.1
  - libhwloc=2.12.1
  - libhwy=1.2.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - libjxl=0.11.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libnetcdf=4.9.2
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libopenblas=0.3.30
  - libopentelemetry-cpp=1.21.0
  - libopentelemetry-cpp-headers=1.21.0
  - libparquet=21.0.0
  - libpng=1.6.50
  - libprotobuf=6.31.1
  - libre2-11=2025.07.22
  - librsvg=2.58.4
  - librttopo=1.1.0
  - libsanitizer=14.3.0
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-devel_linux-64=14.3.0
  - libstdcxx-ng=15.1.0
  - libthrift=0.22.0
  - libtiff=4.7.0
  - libutf8proc=2.10.0
  - libuuid=2.38.1
  - libuv=1.51.0
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxkbcommon=1.10.0
  - libxml2=2.13.8
  - libzip=1.11.2
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - linkify-it-py=2.0.3
  - llvm-openmp=20.1.8
  - llvmlite=0.44.0
  - locket=1.0.0
  - logical-unification=0.4.6
  - lz4=4.4.4
  - lz4-c=1.10.0
  - lzo=2.10
  - mapclassify=2.10.0
  - markdown=3.8.2
  - markdown-it-py=3.0.0
  - markupsafe=3.0.2
  - matplotlib-base=3.10.5
  - matplotlib-inline=0.1.7
  - mdit-py-plugins=0.4.2
  - mdurl=0.1.2
  - metpy=1.7.0
  - minikanren=1.0.5
  - minizip=4.0.10
  - mistune=3.1.3
  - mkl=2024.2.2
  - mkl-service=2.5.2
  - msgpack-python=1.1.1
  - multidict=6.6.3
  - multimethod=2.0
  - multipledispatch=0.6.0
  - munkres=1.1.4
  - muparser=2.3.5
  - mystmd=1.6.0
  - narwhals=2.0.1
  - nbclient=0.10.2
  - nbconvert-core=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - netcdf4=1.7.2
  - networkx=3.5
  - nlohmann_json=3.12.0
  - nodejs=24.4.1
  - notebook-shim=0.2.4
  - numba=0.61.2
  - numcodecs=0.15.1
  - numpy=2.2.6
  - openblas=0.3.30
  - openjpeg=2.5.3
  - openssl=3.5.2
  - orc=2.2.0
  - overrides=7.7.0
  - packaging=25.0
  - pandas=2.3.1
  - pandocfilters=1.5.0
  - panel=1.7.5
  - pango=1.56.4
  - param=2.2.1
  - parso=0.8.4
  - partd=1.4.2
  - patsy=1.0.1
  - pcre=8.45
  - pcre2=10.45
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pint=0.24.4
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.3.8
  - pluggy=1.6.0
  - pooch=1.8.2
  - pqdm=0.2.0
  - prettytable=3.16.0
  - proj=9.6.2
  - prometheus-cpp=1.3.0
  - prometheus_client=0.22.1
  - prompt-toolkit=3.0.51
  - propcache=0.3.1
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pyarrow=21.0.0
  - pyarrow-core=21.0.0
  - pycparser=2.22
  - pyct=0.5.0
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pygments=2.19.2
  - pygmt=0.16.0
  - pymc=5.25.1
  - pymc-base=5.25.1
  - pyogrio=0.11.0
  - pyparsing=3.2.3
  - pyproj=3.7.1
  - pyshp=3.0.0
  - pysocks=1.7.1
  - pystac=1.13.0
  - pystac-client=0.9.0
  - pytensor=2.31.7
  - pytensor-base=2.31.7
  - pytest=8.4.1
  - python=3.13.5
  - python-cmr=0.13.0
  - python-dateutil=2.9.0.post0
  - python-fastjsonschema=2.21.1
  - python-graphviz=0.21
  - python-json-logger=2.0.7
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - pyviz_comms=3.0.6
  - pywavelets=1.9.0
  - pyyaml=6.0.2
  - pyzmq=27.0.1
  - qhull=2020.2
  - rasterio=1.4.3
  - rav1e=0.7.1
  - re2=2025.07.22
  - readline=8.2
  - referencing=0.36.2
  - requests=2.32.4
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rfc3987-syntax=1.1.0
  - rich=14.1.0
  - rioxarray=0.19.0
  - rpds-py=0.27.0
  - s2n=1.5.23
  - s3fs=2025.7.0
  - s3transfer=0.13.1
  - scikit-image=0.25.2
  - scikit-learn=1.7.1
  - scipy=1.16.0
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - send2trash=1.8.3
  - setuptools=80.9.0
  - shapely=2.1.1
  - six=1.17.0
  - snappy=1.2.2
  - sniffio=1.3.1
  - snuggs=1.4.7
  - sortedcontainers=2.4.0
  - soupsieve=2.7
  - sqlite=3.50.4
  - stack_data=0.6.3
  - statsmodels=0.14.5
  - svt-av1=3.0.2
  - sysroot_linux-64=2.17
  - tbb=2021.13.0
  - tblib=3.1.0
  - terminado=0.18.1
  - threadpoolctl=3.6.0
  - tifffile=2025.6.11
  - tinycss2=1.4.0
  - tinynetrc=1.3.1
  - tk=8.6.13
  - tomli=2.2.1
  - toolz=1.0.0
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - types-python-dateutil=2.9.0.20250708
  - typing-extensions=4.14.1
  - typing-inspection=0.4.1
  - typing_extensions=4.14.1
  - typing_utils=0.1.0
  - tzdata=2025b
  - uc-micro-py=1.0.3
  - ujson=5.10.0
  - universal_pathlib=0.2.6
  - uri-template=1.3.0
  - uriparser=0.9.8
  - urllib3=2.5.0
  - virtualizarr=1.2.0
  - wayland=1.24.0
  - wcwidth=0.2.13
  - webcolors=24.11.1
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - widgetsnbextension=4.0.14
  - wrapt=1.17.2
  - xarray=2025.7.1
  - xarray-einstats=0.9.1
  - xerces-c=3.2.5
  - xkeyboard-config=2.45
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.3
  - xorg-libxdamage=1.1.6
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxi=1.8.2
  - xorg-libxinerama=1.1.5
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxtst=1.2.5
  - xyzservices=2025.4.0
  - yaml=0.2.5
  - yarl=1.20.1
  - zarr=2.18.7
  - zeromq=4.3.5
  - zfp=1.0.1
  - zict=3.0.0
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstandard=0.23.0
  - zstd=1.5.7